### ISSUE TITLE
如何减少等价类测试用例和请求参数组合测试用例

### ISSUE THREAD

**Issue by JiangAshao** [chineseluo/opensourcetest#1]
比如注册接口
/api/regist
body:
`{"phone": "13728632983","email":"example@qq.com","password":"123456"}`
### 两个需求:
**1、注册可以用phone，也可以用email，也可以同时填写**
当参数较多时，组合情况就非常多，如何用更少的代码解决重复创建testcase 比如①只有phone，②只有email，③有phone并且有email
**2、同一个参数多种测试用例，如何用更少的代码解决重复创建testcase**
比如email测试 ①qq邮箱②gmail邮箱③outlook邮箱④163邮箱等等
'email':["example@qq.com","example@gmail.com","example@outlook.com","example@163.com"]

**Comment by chineseluo** [comment]
参考pytest的注解@pytest.mark.parametrize()来解决你的问题
