### ISSUE TITLE
json活数据的添加方式希望能够深入添加

### ISSUE THREAD

**Issue by HaoGe20011216** [chineseluo/opensourcetest#3]
期望 能够以 dice的方式来进行深度定位添加数据   

{
“Param”：[
                    {
                      "Key": "string",
                      "Value": "string",
                      "Type": 0
                    }， 
                    “data”： “hello”
                  ]
}

如 要在Param下面的第零个值里面添加数据：{
                (json["Param"][0], {"ss_key": int(time.time())}),   
}

前面的json是固定写法

结果：
{
“Param”：[
                    {
                      "Key": "string",
                      "Value": "string",
                      "Type": 0,
                      "ss_key": "1234566456"，
                    }，
                    “data”： “hello”
                  ]
}

**Comment by chineseluo** [comment]
已新增该特性，问题关闭
