### ISSUE TITLE
allure报告log中文乱码,  已用于生产环境,希望修复,框架非常好用

### ISSUE THREAD

**Issue by fei92test** [chineseluo/opensourcetest#5]
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>·þÎñÆ÷´íÎó</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>405 - ²»ÔÊÐíÓÃÓÚ·ÃÎÊ´ËÒ³µÄ HTTP Î½´Ê¡£</h2>
  <h3>ÄúÒª²éÕÒµÄÒ³ÃæÎÞ·¨ÏÔÊ¾£¬ÒòÎª³¢ÊÔ·ÃÎÊÊ±Ê¹ÓÃÁËÎÞÐ§·½·¨(HTTP Î½´Ê)¡£</h3>
 </fieldset></div>
</div>
</body>
</html>

木神大佬:   接口返回有中文时,在log里面乱码显示,希望迭代修复,

**Comment by chineseluo** [comment]
requests响应的response为html时，未对其中的中文进行gb2312编码处理

**Comment by chineseluo** [comment]
请下载0.3.6版本，已下载的请更新
